<!DOCTYPE html>
<html>
    <head>
        <!-- HTML5 -->
        <meta charset="utf-8">  
        <!-- HTML 4.x -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

        <link rel="stylesheet" href="index.css">

        <link rel="icon" href="images/logo.png">
        
        <title>Stickflix</title>
    </head>
    <body>